[package]
name = "r_vector"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
r_float = { git = "https://github.com/elapuestojoe/r_float", branch = "main" }